spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/ged-app-unirio-db
        username: postgres
        password: 1234
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: none
            use-new-id-generator-mappings: false
        show-sql: true
    elasticsearch:
        rest:
            uris: http://localhost:9200
    jackson:
        serialization.indent_output: true

security:
    auth:
        client-id: #auth client-id
    jwt:
        header: Authorization
        prefix: Bearer
        secret: #jwt secret key
        expiration: 43200