spring:
    datasource:
        url: ${DB_POSTGRESQL_URL}
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: none
            use-new-id-generator-mappings: false
        show-sql: true
    elasticsearch:
        uris: ${DB_ELASTICSEARCH_URL}
    jackson:
        serialization:
            indent_output: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 20MB
            max-request-size: 20MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties.mail.smtp:
            auth: true
            starttls.enable: true

security:
    auth:
        client-id: ${AUTH_CLIENTID}
    jwt:
        header: Authorization
        prefix: Bearer
        secret: ${JWT_SECRET_KEY}
        expiration: 3600
    web:
        allowedOrigins: ${ALLOWED_ORIGINS}

application:
    tesseract:
        language: ${TESSERACT_LANG:por+eng}
    storage:
        path: ${FILE_STORAGE_PATH:}

logging:
    level:
        root: info
        sql: info
        web: info