spring:
    datasource:
        url: ${DATABASE.POSTGRESQL.PATH}
        username: ${DATABASE.POSTGRESQL.USERNAME}
        password: ${DATABASE.POSTGRESQL.PASSWORD}
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: none
            use-new-id-generator-mappings: false
        show-sql: true
    elasticsearch:
        rest:
            uris: ${DATABASE.ELASTICSEARCH.PATH}
    jackson:
        serialization:
            indent_output: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 20MB
            max-request-size: 20MB
            location: ${FILE.STORAGE.PATH}
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL.USERNAME}
        password: ${MAIL.PASSWORD}
        properties.mail.smtp:
            auth: true
            starttls.enable: true

security:
    auth:
        client-id: ${AUTH.CLIENTID}
    jwt:
        header: Authorization
        prefix: Bearer
        secret: ${JWT.SECRET.KEY}
        expiration: 3600

application:
    storage:
        path: ${FILE.STORAGE.PATH}

logging:
    level:
        root: info
        sql: info
        web: info